trigger:
  - main
pool:
  vmImage: ubuntu-latest
stages: 
  - stage: build code
    displayName: build
    jobs:
      - job: first job
        displayName: first job
        steps:
           - task: first step
      - job: second job
        steps:
          - task: second task

    
